import type { Metadata } from "next";
import { bagoss, sohne, graphik, agrandir } from "@/fonts";

import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bagoss.variable} ${sohne.variable} ${graphik.variable} ${agrandir.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
